package tci.demo.week1;

import java.util.List;

/**
 * Group represents a group of unique students, e.g. a class e-s72,
 * and is uniquely identified by its name.
 * When a group has no name yet, it automatically is given
 * the temporary name "unknown". The name can be changed later.
 * a student can be added to a group. A mentor can be added to the group, in this case, all students
 * get assigned this mentor
 *
 */
public class Group {

    private String groupName;
    private List<Student> groupStudents;
    private String groupMentor;

    /** Creates a group with a default name "unknown" */
    public Group() {
        this.groupName = "unknown";
    }

    /** Creates a Group object with a given name.
     * @param name is the name of the group/class, e.g., "e-s72" */
    public Group(String name) {
        this.groupName = name;
    }


    /** Add a student to the group
     * @param student Student to add
     */
    public void addStudent(Student student){
        this.groupStudents.add(student);
    }

    /** Assigns a mentor to all students in this group
     * @param mentor is the mentor of the group */
    public void setMentor(String mentor){
        for (Student s : this.groupStudents) {
            s.studentMentor = mentor;
        }
    }

    /******************************************************
     *
     *   GETTERS/SETTERS CODE IS GENERATED BY INTELLIJ,
     *   AND UNTOUCHED BY PEOPLE.
     *   THE BEHAVIOUR OF THIS CODE DOES NOT HAVE TO BE TESTED.
     *
     ********************************************************/

    // TODO

    /******************************************************
     *
     *   OTHER CODE GENERATED BY INTELLIJ,
     *   BUT BASED ON INPUT OF A PROGRAMMER.
     *   THE BEHAVIOUR OF THIS CODE HAS TO BE TESTED.
     *   (but not present to keep demo code short)
     *
     ********************************************************/

    // TODO


}
